# Docker swarm stack 部署文件
version: "3.4"
services:
  zxb-message-thrift-service:
    image: 192.168.1.139:8080/micro-service/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
  zxb-user-thrift-service:
    image: 192.168.1.139:8080/micro-service/user-service:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8001:8001"
  zxb-user-edge-service:
    image: 192.168.1.139:8080/micro-service/user-edge-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
#    ports:
#      - "8082:8082"
      # 只允许安装在leader节点上
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/user/login"]
      interval: 60s
      timeout: 10s
      retries: 3
    depends_on:
      - zxb-user-thrift-service
      - zxb-message-thrift-service
  zxb-course-dubbo-service:
    image: 192.168.1.139:8080/micro-service/course-dubbo-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    depends_on:
      - zxb-user-thrift-service
  zxb-course-edge-service:
    image: 192.168.1.139:8080/micro-service/course-edge-service:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8084:8084"
    depends_on:
      - zxb-user-edge-service
  zxb-api-gateway-zuul:
    image: 192.168.1.139:8080/micro-service/api-gateway-zuul:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8085:8085"
    depends_on:
      - zxb-user-edge-service
      - zxb-course-edge-service
networks:
  default:
    external:
      name: my-overlay


# docker swarm + nginx，挂载nginx.conf配置文件
  docker run -idt 80:80 -v `pwd`/nginx.conf://etc/nginx/conf.d/default.conf nginx
# 查看容器配置
  docker run -it --entrypoint bash nginx
# 启动或更新服务
  docker stack deploy -c micro-service.yml ms