mail:
  smtp:
    #服务器主机名
    host: smtp.qq.com
    #你的邮箱地址
    username: 171980062@qq.com
    #授权码
    password: nvgzpmqoxcwjbjgf
    #编码格式
    defaultEncoding: utf-8
    #是否进行用户名密码校验
    auth: true
    #设置超时时间
    timeout: 20000

server:
  port: 8081