spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "@Wwindows8"
#    url: jdbc:mysql://${mysql.address}:3306/db_user?characterEncoding=utf-8&serverTimezone=GMT
    url: jdbc:mysql://192.168.1.119:3306/db_user?characterEncoding=utf-8&serverTimezone=GMT
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
server:
  port: 8080
thrift:
  port: 8001
