spring:
  application:
    name: course-edge
  # dubbo config
  dubbo:
    application:
      name: course-consumer-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      port: 20880
server:
  port: 8084

