spring:
  application:
    name: course-edge
  # dubbo config
  dubbo:
    application:
      name: course-consumer-service
    registry:
      address: zookeeper://192.168.1.119:2181
#      address: zookeeper://${zookeeper.address}:2181
    protocol:
      port: 20880
server:
  port: 8084

user:
  edge:
    service:
      addr: zxb-user-edge-service:8082
#      addr: lb.zxb.com:8003

