server:
  port: 8082

spring:
  application:
    name: user-edge-service
  redis:
    timeout: 30000
thrift:
  user:
    ip: 127.0.0.1
    port: 8080
  message:
    ip: 127.0.0.1
    port: 8081

cache:
  timeout: 60
  cacheExpirations:
    myControlledCache: 180