server:
  port: 8082

spring:
  application:
    name: user-edge-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: ${redis.address}
thrift:
  user:
#    ip: 127.0.0.1
    ip: zxb-user-thrift-service
    port: 8080
  message:
#    ip: 127.0.0.1
    ip: zxb-message-thrift-service
    port: 8081

cache:
  timeout: 60
  cacheExpirations:
    myControlledCache: 180